server:
  port: 8080
spring:
  application:
    name: ExchangeRateService
  threads:
    virtual:
      enabled: true
exchange:
  api-url: "https://api.exchangerate.host"
  additional-api-url: "/latest?base="
  symbols:  "/symbols"

